In [1]:
symbols = '$%#@%'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

In [2]:
codes

[36, 37, 35, 64, 37]

In [3]:
symbols = '$%#@%'
codes = [ord(symbol) for symbol in symbols]

In [4]:
codes

[36, 37, 35, 64, 37]

In [7]:
x= 'ABC'
dummy = [ord(x) for x in x]
x

'ABC'

In [8]:
dummy

[65, 66, 67]

In [13]:
symbols = '$%#@&~'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 37]
beyond_ascii

[64, 38, 126]

In [15]:
beyond_ascii = list(filter(lambda c: c >37, map(ord, symbols)))
beyond_ascii

[64, 38, 126]

In [17]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [19]:
tshirts = [(color, size) for size in sizes
                         for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

### 2.2.4 제너레이터 표현식
### 제너레이션 표현식은 메모리를 더 적게 사용한다.

In [21]:
symbols = '$%#@&~'
tuple(ord(symbol) for symbol in symbols)

(36, 37, 35, 64, 38, 126)

In [22]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 37, 35, 64, 38, 126])

In [23]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirts in ('%s %s' % (c,s) for c in colors for s in sizes):
    print(tshirts)

black S
black M
black L
white S
white M
white L


### 2.3 튜플은 단순한 불변 리스트가 아니다

In [26]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32400, 0.66, 8014)
traveler_ids = [('USA','31195855'), ('BRA','CE342567'), ('ESP', 'XS205856')]
for passort in sorted(traveler_ids):
    print('%s/%s' % passort)

BRA/CE342567
ESP/XS205856
USA/31195855


In [27]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [28]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude

33.9425

In [29]:
longitude

-118.408056

In [31]:
divmod(20,8)

(2, 4)

In [35]:
t = (20,8)
quotient, reminder = divmod(*t)
quotient, reminder

(2, 4)

In [40]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [43]:
a,b,*rest =range(5)
a,b,rest

(0, 1, [2, 3, 4])

In [44]:
a,b,*rest = range(3)
a,b,rest

(0, 1, [2])

In [45]:
a,b,*rest = range(2)
a,b,rest

(0, 1, [])

In [46]:
a,*body,c,d = range(5)
a,body,c,d

(0, [1, 2], 3, 4)

In [47]:
*head,b,c,d = range(5)
head,b,c,d

([0, 1], 2, 3, 4)

In [53]:
metro_areas = [
    ('Toyko', 'JP', 36.933, (35.698722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newmark', 'US', 20.104, (40.808611, -74.202386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat','long'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitide, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |    lat    |   long   
Mexico City     |   33.9425 |  -99.1333
New York-Newmark |   33.9425 |  -74.2024
Sao Paulo       |   33.9425 |  -46.6358


In [54]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [55]:
tokyo.population

36.933

In [56]:
tokyo.coordinates

(35.689722, 139.691667)

In [57]:
tokyo[1]

'JP'

In [58]:
City._fields

('name', 'country', 'population', 'coordinates')

In [62]:
LatLong = namedtuple('LatLong','lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889,77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

In [63]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


### 2.4 슬라이싱

In [66]:
l = [10,20,30,40,50,60]
l[:2]

[10, 20]

In [67]:
l[2:]

[30, 40, 50, 60]

In [68]:
l[:3]

[10, 20, 30]

In [69]:
l[3:]

[40, 50, 60]

In [70]:
s='bicycle'
s[::3]

'bye'

In [71]:
s[::-1]

'elcycib'

In [73]:
s[::-2]

'eccb'

In [76]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [80]:
l[2:5] = [20,30]
l

[0, 1, 20, 30, 6, 7, 8, 9]

In [81]:
del l[5:7]
l

[0, 1, 20, 30, 6, 9]

In [83]:
l[3::2]=[11,22]
l

[0, 1, 20, 11, 6, 22]

In [85]:
l[2:5] = [100]
l

[0, 1, 100, 22]

### 2.5 시컨스에 덧셈과 곱셈 연산자 사용하기

In [86]:
ㅣ=[1,2,3]
ㅣ*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [87]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [88]:
board = [['_']*3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [89]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

### 동일한 리스트에 대한 세 개의 참조를 가진 리스트는 쓸모없다.
### 내포된 리스트를 가진 리스트를 초기화 하는 경우 지능형 리스를 사용하는 것이 가장 좋다

In [92]:
weird_board = [['_']*3]*3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [93]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [98]:
row = ['_']*3
board = []
for i in range(3):
    board.append(row)

In [99]:
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [101]:
board =[]
for i in range(3):
    row = ['_']*3
    board.append(row)

In [102]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

### 2.6 시퀀스의 복합 할당

In [103]:
l= [1,2,3]
id(l)

4436708616

In [104]:
l*=2
l

[1, 2, 3, 1, 2, 3]

In [105]:
id(l)

4436708616

In [106]:
t=(1,2,3)
id(t)

4436422728

In [107]:
t*=2
id(t)

4435965128

In [108]:
t=(1,2,[30,40])
t[2] += [50,60]

TypeError: 'tuple' object does not support item assignment

In [109]:
t

(1, 2, [30, 40, 50, 60])

### 2.7 list.sort()와 sorted() 내장 함수

In [110]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [112]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [113]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [114]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [115]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [116]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [117]:
fruits.sort()

In [118]:
fruits


['apple', 'banana', 'grape', 'raspberry']

### 2.8 정렬된 시퀀스를 bisect로 관리하기

In [121]:
import bisect
import sys

HAYSTACK = [1,4,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT ='{0:2d} @ {1:2d} {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * ' |'
        print(ROW_FMT.format(needle, position, offset))
        
if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
        
    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ''.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect
haystack ->  1 4 6 8121520212323262930
31 @ 13  | | | | | | | | | | | | |31
30 @ 13  | | | | | | | | | | | | |30
29 @ 12  | | | | | | | | | | | |29
23 @ 10  | | | | | | | | | |23
22 @  8  | | | | | | | |22
10 @  4  | | | |10
 8 @  4  | | | |8 
 5 @  2  | |5 
 2 @  1  |2 
 1 @  1  |1 
 0 @  0 0 


In [122]:
def grade(score, breakpoints=[60,70,80,90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

### 2.9.3

In [123]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
type(a)

numpy.ndarray

In [125]:
a.shape

(12,)

In [127]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a[2]

array([ 8,  9, 10, 11])

In [129]:
a[2,1]

9

In [130]:
a[:,1]

array([1, 5, 9])

In [131]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [132]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
dq.rotate(3)
dq

deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [135]:
dq.rotate(-4)
dq

deque([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [136]:
dq.appendleft(-1)
dq

deque([-1, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [137]:
dq.extend([11,22,33])
dq

deque([0, 1, 2, 3, 4, 5, 6, 11, 22, 33])

In [138]:
dq.extend([10,20,30,40])
dq

deque([4, 5, 6, 11, 22, 33, 10, 20, 30, 40])